vo=gpu
ao=pulse
hwdec=auto
autofit-larger=96%x92%
autofit-smaller=240x240
correct-downscaling=no
cscale-antiring=0
cscale=bilinear
deband=no
dither-depth=no
dither-depth=no
dscale=bilinear
keepaspect-window=no
osd-font='Roboto Mono'
scale-antiring=0
scale=bilinear
sigmoid-upscaling=no
sub-auto=all
sub-font-size=32
sub-font='TeX Gyre Heros'
sws-allow-zimg=yes
sws-fast=yes
sws-scaler=bilinear
zimg-dither=no
zimg-scaler=bilinear
ytdl-format="bestvideo[height<=1080][fps<=30]+bestaudio/best"
