#!/bin/sh

chosen=$(cut -d ';' -f1 /home/kylert/.local/share/Blista-Kanjo-Emoji/emoji | /home/kylert/.local/share/dmenu-custom/dmenu -i -l 30 | sed "s/ .*//")

[ -z "$chosen" ] && exit

if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	echo -n "$chosen" | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
